{{- if .Values.route.enabled -}}
{{- $fullName := include "app.fullname" . -}}
{{- $routePath := .Values.backend.route.path -}}
{{- $host := .Values.route.host -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
{{- if .Values.route.letsencrypt }}
  annotations:
    kubernetes.io/tls-acme: "true"
{{- end }}
  labels:
    app: {{ template "app.name" . }}-backend
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ $fullName }}-backend
spec:
  host: {{ $host }}
  path: {{ $routePath }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ template "app.fullname" . }}-backend
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - routerName: router
{{- end }}