apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/namespace-mysql.json") . | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "app.name" . }}-mysql
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "app.name" . }}-mysql
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: mysql-data
{{- if .Values.mysql.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "app.fullname" . }}-mysql-data
{{- else }}
          emptyDir: {}
{{- end }}
      containers:
        - name: {{ .Chart.Name }}-mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: database-user
                  name: {{ template "app.name" . }}-mysql
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: {{ template "app.name" . }}-mysql
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: database-name
                  name: {{ template "app.name" . }}-mysql
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-root-password
                  name: {{ template "app.name" . }}-mysql
          ports:
            - containerPort: 5432
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - /usr/libexec/check-container
                - '--live'
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            exec:
              exec:
                command: ["mysql", "-h", "127.0.0.1", "-e", "SELECT 1"]
          volumeMounts:
            - mountPath: /var/lib/mysql/data
              name: mysql-data
          resources:
  {{ toYaml .Values.mysql.resources | indent 12 }}
  {{- with .Values.mysql.nodeSelector }}
nodeSelector:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.mysql.affinity }}
affinity:
  {{ toYaml . | indent 8 }}
  {{- end }}
  {{- with .Values.mysql.tolerations }}
tolerations:
  {{ toYaml . | indent 8 }}
  {{- end }}

