route:
  enabled: true
  host: "tt-manager.apps.baloise.dev"
  letsencrypt: true

mysql:
  enabled: true
  image:
    repository: holzleube/mysql-docker-image
    tag: "2.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3306
  persistence:
    enabled: true
    storageClass: rook-ceph-block
    size: 1.0Gi
  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

backend:
  replicaCount: 1
  appPort: 9000
  image:
    repository: holzleube/turniermanager
    tag: "1.2"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  route:
    enabled: true
    path: /api
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

frontend:
  replicaCount: 1
  appPort: 8080
  image:
    repository: holzleube/turniermanager-client
    tag: "1.2"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  route:
    enabled: true
    path: /
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}


