{{- if .Values.mysql.enabled -}}
{{- $host := printf "%s-%s" (include "app.fullname" . ) "mysql" -}}
apiVersion: v1
data:
  database-name: {{ .Values.mysql.databaseName | b64enc }}
  database-password: {{ .Values.mysql.password | b64enc }}
  database-user: {{ .Values.mysql.user | b64enc }}
  database-host: {{ $host | b64enc }}
  email-host: {{ .Values.email.host | b64enc }}
  email-user: {{ .Values.email.user | b64enc }}
  email-password: {{ .Values.email.password | b64enc }}
kind: Secret
metadata:
  labels:
    app: {{ template "app.name" . }}-mysql
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "app.name" . }}-mysql
type: Opaque
{{- end}}
