app:
  backend:
    replicaCount: 1
    appPort: 8080
    image:
      repository: holzleube/tournamentregistration
      tag: master-f948103
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 80
    route:
      enabled: true
      path: /
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
