route:
  enabled: true
  host: "ttt.wheel.sh"
  letsencrypt: true

mysql:
  enabled: true
  image:
    repository: centos/mysql-57-centos7
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3306
  persistence:
    enabled: true
    storageClass: rook-ceph-block
    size: 1.5Gi
  resources: {}
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

backend:
  replicaCount: 1
  appPort: 8080
  image:
    repository: holzleube/tournamentregistration
    tag: master-3ee4585
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  route:
    enabled: true
    path: /
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}


